### ISSUE TITLE
Null reference exception when using NavigationManager with HeadOutlet

### ISSUE THREAD

**Issue by VictorioBerra** [Garderoben/MudBlazor.Templates#328]
I get:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'

on this line of code:

`<component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />`

This happens when I try and redirect from one of my components:

```csharp
@using System.Web;
@inject NavigationManager Navigation

@code {
    [Parameter]
    public string ReturnUrl { get; set; } = null!;

    protected override async Task OnInitializedAsync()
    {
        var loginEndpoint = "Login?redirectUri=" + HttpUtility.UrlEncode(ReturnUrl);
        Navigation.NavigateTo(loginEndpoint, forceLoad: true);
        await base.OnInitializedAsync();
    }
}
```

**Comment by VictorioBerra** [comment]
A little luck, but still not sure what to do. I found this on another thread: https://github.com/dotnet/aspnetcore/issues/33868#issuecomment-925968851

I notice **both** the [_Host](https://github.com/MudBlazor/Templates/blob/dev/src/.template.base/server/Pages/_Host.cshtml#L1) and the [Index](https://github.com/MudBlazor/Templates/blob/dev/src/.template.mudblazor/defaultblazor/Pages/Index.razor#L1) have `﻿@page "/"` at the top of them.

Any ideas?

**Comment by VictorioBerra** [comment]
Repro: https://github.com/VictorioBerra/MudBlazorHeadOutletIssue

**Comment by ScarletKuro** [comment]
Hi.
I believe the issue is not related to MudBlazor or the Templates, but please correct me if I'm mistaken. The problem seems to be caused by a 17 line in the App.razor: `<MudText Typo="Typo.h3" GutterBottom="true" Style="@($"color:{Theme.Palette.Error};")">Access Denied</MudText>`

By commenting out this line, everything seems to work fine. However, even if you replace it with a different non-native MudBlazor component, such as `<InputFile></InputFile>`, the error still occurs. I'm unable to provide a clear explanation for this behavior, so it would be advisable to ask in the `aspnetcore` repository.

**Comment by VictorioBerra** [comment]
Thank you.
