### ISSUE TITLE
MudBlazor.Templates does not support Blazor webassembly .net7

### ISSUE THREAD

**Issue by mceylan35** [Garderoben/MudBlazor.Templates#388]
Error: Severity	Code	Description	Project	File	Line	Suppression State
Error		Package 'MudBlazor.Templates 0.6.3' has a package type 'Template' that is not supported by project 'src\Presentation\TradingViewWebHook.WebApp'.

**Comment by ScarletKuro** [comment]
Hi.
Really unclear description, missing details on what you are trying to achieve and no reproduction project.
If you are trying to install `MudBlazor.Templates` from nuget to you project, then the error is correct.
`MudBlazor.Templates` is not suppose to be added as reference because this is a template not a reusable library, you just add it to dotnet:
`dotnet new install MudBlazor.Templates`
and then you can create a mublazor default project by using the command line:
`dotnet new mudblazor --host wasm --name MyApplication` as example

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
